nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.3.cjs

npmScopes:
  minimus:
    npmAlwaysAuth: true
    npmAuthToken: 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
    npmRegistryServer: https://npm.pkg.github.com
